### ISSUE TITLE
Explanatory Agent - Automated Testing Plan

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/TranslatorPM#102]
Automated Testing Plans are due by the Spring Relay.

Please submit your plan in your team folder: https://drive.google.com/drive/folders/1wH2njrx6ICjRh879WAfh3UgWKuXLv0os?usp=sharing

The Program Milestone reads:
An automated testing plan to verify service availability and basic knowledge retrieval has been developed for each Translator tool [your team maintains], with detailed documentation on the expected results of each test.

@NCATSTranslator/explanatory-agent

**Comment by ehinderer** [comment]
General GitHub question... I self-assigned this issue to help remind me to bring it up with my teams, but it is not showing up under my "reason:assigned" filter. Any idea why?

**Comment by sstemann** [comment]
huh - what's odd is that it works when i use "reason:assigned" maybe you could save a link to something like this instead?

https://github.com/NCATSTranslator/TranslatorPM/issues?q=assignee%3Aehinderer+label%3A%22Explanatory+Agent

**Comment by ehinderer** [comment]
I see now, i need to respond to each thread before it shows up... strange. I still prefer it to bookmarking links. That's a whole other mess.

**Comment by nlharris** [comment]
@ehinderer I'm not sure how you're looking for issues assigned to you, but https://github.com/issues/assigned should show you them (including ones you haven't commented on yet). I just tested by self-assigning myself an issue and it shows up in my assigned list. See if that works for you.

**Comment by ehinderer** [comment]
Yes I see it there, but could not see it under the "assigned" tab on the notifications screen. 
![Capture](https://user-images.githubusercontent.com/4601958/108559029-c3447000-72c8-11eb-911a-e64f9898e574.JPG)

**Comment by nlharris** [comment]
Huh. Interesting. I'd never looked at the "assigned" tab before. Mine (https://github.com/notifications?query=reason%3Aassign) shows me 2 open issues and 7 closed. Meanwhile, "my issues" (https://github.com/issues/assigned) shows me 6 open issues. I suggest using "my issues" rather than the Assign tab, but it's odd that they're so different.

**Comment by nlharris** [comment]
Ok--I figured it out! The filters on the Notifications screen don't filter issues, they filter notifications in your GitHub inbox.
![Screen Shot 2021-02-19 at 3 48 17 PM](https://user-images.githubusercontent.com/348704/108573623-f5a29d00-72c9-11eb-9765-4f189ff396da.png)
Whether or not you get one of those notifications when you're assigned an issue probably depends on how you have notifications set up. So it's not a reliable place to look for issues assigned to you. It's definitely misleading, because it does look like it's going to show you issues assigned to you!
